* Added libraries with helper functions * Created first map * Started some game logic

diff --git a/lib/map b/lib/map
--- a/lib/map
+++ b/lib/map
@@ -22,47 +22,21 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+# PRAGMA: Use once and only as sourced
+if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The utils can only be sourced!"; exit 1; fi
+if [ -n "$SOURCE_MAP" ]; then return; fi
 
-## How does this game work?
-# GAME-LOOP
-#  - check for keyboard input
-#  - update user
-#  - update ghosts
-#  - paint to screen
-# REPEAT
+source "$SCRIPT_DIR/lib/utils"
 
-## GLOBALS
-# Base dir for the game
-SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
-# The initial map read from the filesystem. Empty until read
-FULL_MAP=
-# Last registered key from keyboard
-KEY_READ=
+## Reads in a map file, stores in the FULL_MAP array
+# $1: path to file
+read-map() {
+	filename="$1"
 
-source "$SCRIPT_DIR/lib/keyboard"
-source "$SCRIPT_DIR/lib/map"
-source "$SCRIPT_DIR/lib/statusbar"
+	[[ -f "$filename" ]] || error "Map file not found: $filename"
 
-main() {
-	statusbar-setup
-	keyboard-setup
-	screen-erase-all
-	screen-hide-cursor
-
-	read-map "$SCRIPT_DIR/maps/map1"
-	echo "${FULL_MAP[@]}"
-
-	while [[ "$KEY_READ" != "key-end" ]]; do
-		# Update KEY_READ variable
-		local new_key
-		read -rs -u 3 -t .001 new_key
-
-		if [[ -n $new_key ]]; then
-			KEY_READ=$new_key
-		fi
-	done;
-
-	screen-show-cursor
+	mapfile FULL_MAP < "$filename"
 }
 
-main
+
+export SOURCE_MAP=1
diff --git a/lib/traps b/lib/traps
--- a/lib/traps
+++ b/lib/traps
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 #
 # MIT License
 #
@@ -22,47 +22,31 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+# PRAGMA: Use once and only as sourced
+if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The traps.sh can only be sourced!"; exit 1; fi
+if [ ! -z "${SOURCE_TRAPS:-}" ]; then return; fi
 
-## How does this game work?
-# GAME-LOOP
-#  - check for keyboard input
-#  - update user
-#  - update ghosts
-#  - paint to screen
-# REPEAT
+source "$SCRIPT_DIR/lib/utils"
 
-## GLOBALS
-# Base dir for the game
-SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
-# The initial map read from the filesystem. Empty until read
-FULL_MAP=
-# Last registered key from keyboard
-KEY_READ=
-
-source "$SCRIPT_DIR/lib/keyboard"
-source "$SCRIPT_DIR/lib/map"
-source "$SCRIPT_DIR/lib/statusbar"
-
-main() {
-	statusbar-setup
-	keyboard-setup
-	screen-erase-all
-	screen-hide-cursor
-
-	read-map "$SCRIPT_DIR/maps/map1"
-	echo "${FULL_MAP[@]}"
-
-	while [[ "$KEY_READ" != "key-end" ]]; do
-		# Update KEY_READ variable
-		local new_key
-		read -rs -u 3 -t .001 new_key
-
-		if [[ -n $new_key ]]; then
-			KEY_READ=$new_key
-		fi
-	done;
-
-	screen-show-cursor
+## Append a function to be called when a trap happens. This way
+## multiple independent function may handle the same trap from
+## each their own library without knowledge of eachother.
+# $1: Function to call
+# $2: Name of trap (like regular bash trap, eg. WINCH, EXIT, ...)
+trap_add() {
+    trap_add_cmd=$1; shift || fatal "${FUNCNAME} usage error"
+    for trap_add_name in "$@"; do
+        trap -- "$(
+            # helper fn to get existing trap command from output
+            # of trap -p
+            extract_trap_cmd() { printf '%s\n' "$3"; }
+            # print the new trap command
+            printf '%s\n' "${trap_add_cmd}"
+            # print existing trap command with newline
+            eval "extract_trap_cmd $(trap -p "${trap_add_name}")"
+        )" "${trap_add_name}" \
+            || fatal "unable to add to trap ${trap_add_name}"
+    done
 }
 
-main
+SOURCE_TRAPS=1
diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -22,47 +22,35 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+# PRAGMA: Use once and only as sourced
+if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The utils can only be sourced!"; exit 1; fi
+if [ -n "$SOURCE_UTILS" ]; then return; fi
 
-## How does this game work?
-# GAME-LOOP
-#  - check for keyboard input
-#  - update user
-#  - update ghosts
-#  - paint to screen
-# REPEAT
 
-## GLOBALS
-# Base dir for the game
-SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
-# The initial map read from the filesystem. Empty until read
-FULL_MAP=
-# Last registered key from keyboard
-KEY_READ=
-
-source "$SCRIPT_DIR/lib/keyboard"
-source "$SCRIPT_DIR/lib/map"
-source "$SCRIPT_DIR/lib/statusbar"
-
-main() {
-	statusbar-setup
-	keyboard-setup
-	screen-erase-all
-	screen-hide-cursor
-
-	read-map "$SCRIPT_DIR/maps/map1"
-	echo "${FULL_MAP[@]}"
-
-	while [[ "$KEY_READ" != "key-end" ]]; do
-		# Update KEY_READ variable
-		local new_key
-		read -rs -u 3 -t .001 new_key
-
-		if [[ -n $new_key ]]; then
-			KEY_READ=$new_key
-		fi
-	done;
-
-	screen-show-cursor
+## Output error message to STDOUT and halts program with exit code 1
+# $1: message to output
+error() {
+    message="$1"
+    echo "$message" > /dev/stderr
+    exit 1
 }
 
-main
+fatal() {
+    error "$1"
+}
+
+## Create a temporary fifi pipe
+# $OUTPUT: path of create pipe
+mktemp_fifo() {
+    local pipe
+    pipe="$(mktemp -u)"
+
+    while [[ -e "$pipe" ]]; do
+        pipe="$(mktemp -u)"
+    done
+
+    mkfifo "$pipe" || fatal "failed to create pipe $PIPE"
+    echo "$pipe"
+}
+
+export SOURCE_UTILS=1
